// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bhergnyfmwmxjrijiwoc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJoZXJnbnlmbXdteGpyaWppd29jIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzk4Mzk3MjIsImV4cCI6MjA1NTQxNTcyMn0.Xk6EbvN9QGcn78w8JDSeawUxgkbrcItR8pyO8SHKCHY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);